PrepareCheckout non-head references
Byron/gitoxide pull request #1403
Opened 2024-06-16 17:08 UTC by Fernthedev

This PR adds support for checking non-head references such as commits, tags, branches etc. using `repo.find_reference()`. 

While I preferred using `Reference` as a parameter rather than `&BStr`, I kept running into lifetime issues related to borrows with `self.repo` in PrepareCheckout. 

At the time of writing this, it seems this solution is incomplete as the checkout does not set the git repo to checkout the reference. Specifically (excuse my lack of git terminology) `git status` is still set to track the HEAD reference it seems. However, the files are correctly cloned.
```
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   qpm.shared.json
        modified:   src/logger.cpp
```

I hope this PR isn't too messy, though feel free to ask for changes to follow the repo's code style. Thanks!

In reference to discussion https://github.com/Byron/gitoxide/discussions/1389

2024-06-16 17:16 UTC, Byron commented
Thanks for giving it a shot!

I strongly recommend to try  and find existing tests to adapt and to test the new functionality with them. This also allows to double-check the outcome. That way, turnaround times will be much shorter.

2024-06-18 00:03 UTC, Fernthedev commented
Hi so I attempted to add the unit test as requested, though unfortunately I'm not very familiar with the test setup and rather confused with everything. I tried using the generated repositories for the test and `git branches -a` shows multiple branches. However, the test fails and it seems to only recognize `main`.

I apologize though I'll mention that I did allow maintainers to modify the branch in the case you'd like to do the finish touches. Thanks!


```shell
git branch -a 

 a
  b
  c
  d
  e
  f
  g
  h
  i
  j
* main
```

2024-06-18 05:01 UTC, Byron requested changes
It does look like a struggle, and I am happy to finish the PR.

Before that,  could you solve the linting failure and maybe setup tooling to auto-format code?

2024-06-19 15:55 UTC, Fernthedev commented
I formatted the files and it CI seems to be ok now (other than the broken test)

Appreciate your patience

2024-06-20 07:12 UTC, Byron commented
I have started working on this and plan to force-push a couple of times. It's probably best to not interact with this PR with more than comments until it is merged.

2024-06-20 17:41 UTC, Byron approved these changes
This certainly looks a tiny bit different than how it started out, and was quite hard even for me as I only had vague memory on the 'prior art' within the codebase. Fortunately, everything turned out to be easy once I rediscovered the facilities that were already available.

2024-06-20 18:03 UTC, merged